/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as LocalIndexRouteImport } from './routes/local.index'
import { Route as LocalAgentsIndexRouteImport } from './routes/local-agents.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as ComputersIndexRouteImport } from './routes/computers.index'
import { Route as BridgeIndexRouteImport } from './routes/bridge.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as MemoriesMemoryIdRouteImport } from './routes/memories.$memoryId'
import { Route as LocalTokenIdRouteImport } from './routes/local.$tokenId'
import { Route as LocalAgentsTokenIdRouteImport } from './routes/local-agents.$tokenId'
import { Route as IntegrationsAccountIdRouteImport } from './routes/integrations.$accountId'
import { Route as DebugRemoteRouteImport } from './routes/debug.remote'
import { Route as ComputersComputerIdRouteImport } from './routes/computers.$computerId'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as IntegrationsOcAccountIdRouteImport } from './routes/integrations.oc.$accountId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as ComputersComputerIdAgentsAgentKindRouteImport } from './routes/computers.$computerId_.agents.$agentKind'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIndexRoute = LocalIndexRouteImport.update({
  id: '/local/',
  path: '/local/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAgentsIndexRoute = LocalAgentsIndexRouteImport.update({
  id: '/local-agents/',
  path: '/local-agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputersIndexRoute = ComputersIndexRouteImport.update({
  id: '/computers/',
  path: '/computers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeIndexRoute = BridgeIndexRouteImport.update({
  id: '/bridge/',
  path: '/bridge/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesMemoryIdRoute = MemoriesMemoryIdRouteImport.update({
  id: '/memories/$memoryId',
  path: '/memories/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalTokenIdRoute = LocalTokenIdRouteImport.update({
  id: '/local/$tokenId',
  path: '/local/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAgentsTokenIdRoute = LocalAgentsTokenIdRouteImport.update({
  id: '/local-agents/$tokenId',
  path: '/local-agents/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAccountIdRoute = IntegrationsAccountIdRouteImport.update({
  id: '/integrations/$accountId',
  path: '/integrations/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRemoteRoute = DebugRemoteRouteImport.update({
  id: '/debug/remote',
  path: '/debug/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputersComputerIdRoute = ComputersComputerIdRouteImport.update({
  id: '/computers/$computerId',
  path: '/computers/$computerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsOcAccountIdRoute = IntegrationsOcAccountIdRouteImport.update({
  id: '/integrations/oc/$accountId',
  path: '/integrations/oc/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputersComputerIdAgentsAgentKindRoute =
  ComputersComputerIdAgentsAgentKindRouteImport.update({
    id: '/computers/$computerId_/agents/$agentKind',
    path: '/computers/$computerId/agents/$agentKind',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/computers/$computerId': typeof ComputersComputerIdRoute
  '/debug/remote': typeof DebugRemoteRoute
  '/integrations/$accountId': typeof IntegrationsAccountIdRoute
  '/local-agents/$tokenId': typeof LocalAgentsTokenIdRoute
  '/local/$tokenId': typeof LocalTokenIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/bridge/': typeof BridgeIndexRoute
  '/computers/': typeof ComputersIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/local-agents/': typeof LocalAgentsIndexRoute
  '/local/': typeof LocalIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/oc/$accountId': typeof IntegrationsOcAccountIdRoute
  '/computers/$computerId/agents/$agentKind': typeof ComputersComputerIdAgentsAgentKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/computers/$computerId': typeof ComputersComputerIdRoute
  '/debug/remote': typeof DebugRemoteRoute
  '/integrations/$accountId': typeof IntegrationsAccountIdRoute
  '/local-agents/$tokenId': typeof LocalAgentsTokenIdRoute
  '/local/$tokenId': typeof LocalTokenIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/agents': typeof AgentsIndexRoute
  '/bridge': typeof BridgeIndexRoute
  '/computers': typeof ComputersIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/local-agents': typeof LocalAgentsIndexRoute
  '/local': typeof LocalIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/oc/$accountId': typeof IntegrationsOcAccountIdRoute
  '/computers/$computerId/agents/$agentKind': typeof ComputersComputerIdAgentsAgentKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/computers/$computerId': typeof ComputersComputerIdRoute
  '/debug/remote': typeof DebugRemoteRoute
  '/integrations/$accountId': typeof IntegrationsAccountIdRoute
  '/local-agents/$tokenId': typeof LocalAgentsTokenIdRoute
  '/local/$tokenId': typeof LocalTokenIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/bridge/': typeof BridgeIndexRoute
  '/computers/': typeof ComputersIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/local-agents/': typeof LocalAgentsIndexRoute
  '/local/': typeof LocalIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/oc/$accountId': typeof IntegrationsOcAccountIdRoute
  '/computers/$computerId_/agents/$agentKind': typeof ComputersComputerIdAgentsAgentKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/auth/verify'
    | '/computers/$computerId'
    | '/debug/remote'
    | '/integrations/$accountId'
    | '/local-agents/$tokenId'
    | '/local/$tokenId'
    | '/memories/$memoryId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/agents/'
    | '/bridge/'
    | '/computers/'
    | '/integrations/'
    | '/knowledge/'
    | '/local-agents/'
    | '/local/'
    | '/memories/'
    | '/skills/'
    | '/tasks/'
    | '/auth/google/callback'
    | '/integrations/oc/$accountId'
    | '/computers/$computerId/agents/$agentKind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/auth/verify'
    | '/computers/$computerId'
    | '/debug/remote'
    | '/integrations/$accountId'
    | '/local-agents/$tokenId'
    | '/local/$tokenId'
    | '/memories/$memoryId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/agents'
    | '/bridge'
    | '/computers'
    | '/integrations'
    | '/knowledge'
    | '/local-agents'
    | '/local'
    | '/memories'
    | '/skills'
    | '/tasks'
    | '/auth/google/callback'
    | '/integrations/oc/$accountId'
    | '/computers/$computerId/agents/$agentKind'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/auth/verify'
    | '/computers/$computerId'
    | '/debug/remote'
    | '/integrations/$accountId'
    | '/local-agents/$tokenId'
    | '/local/$tokenId'
    | '/memories/$memoryId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/agents/'
    | '/bridge/'
    | '/computers/'
    | '/integrations/'
    | '/knowledge/'
    | '/local-agents/'
    | '/local/'
    | '/memories/'
    | '/skills/'
    | '/tasks/'
    | '/auth/google/callback'
    | '/integrations/oc/$accountId'
    | '/computers/$computerId_/agents/$agentKind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ComputersComputerIdRoute: typeof ComputersComputerIdRoute
  DebugRemoteRoute: typeof DebugRemoteRoute
  IntegrationsAccountIdRoute: typeof IntegrationsAccountIdRoute
  LocalAgentsTokenIdRoute: typeof LocalAgentsTokenIdRoute
  LocalTokenIdRoute: typeof LocalTokenIdRoute
  MemoriesMemoryIdRoute: typeof MemoriesMemoryIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BridgeIndexRoute: typeof BridgeIndexRoute
  ComputersIndexRoute: typeof ComputersIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  LocalAgentsIndexRoute: typeof LocalAgentsIndexRoute
  LocalIndexRoute: typeof LocalIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  IntegrationsOcAccountIdRoute: typeof IntegrationsOcAccountIdRoute
  ComputersComputerIdAgentsAgentKindRoute: typeof ComputersComputerIdAgentsAgentKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/': {
      id: '/local/'
      path: '/local'
      fullPath: '/local/'
      preLoaderRoute: typeof LocalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-agents/': {
      id: '/local-agents/'
      path: '/local-agents'
      fullPath: '/local-agents/'
      preLoaderRoute: typeof LocalAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computers/': {
      id: '/computers/'
      path: '/computers'
      fullPath: '/computers/'
      preLoaderRoute: typeof ComputersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge/': {
      id: '/bridge/'
      path: '/bridge'
      fullPath: '/bridge/'
      preLoaderRoute: typeof BridgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$memoryId': {
      id: '/memories/$memoryId'
      path: '/memories/$memoryId'
      fullPath: '/memories/$memoryId'
      preLoaderRoute: typeof MemoriesMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$tokenId': {
      id: '/local/$tokenId'
      path: '/local/$tokenId'
      fullPath: '/local/$tokenId'
      preLoaderRoute: typeof LocalTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-agents/$tokenId': {
      id: '/local-agents/$tokenId'
      path: '/local-agents/$tokenId'
      fullPath: '/local-agents/$tokenId'
      preLoaderRoute: typeof LocalAgentsTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$accountId': {
      id: '/integrations/$accountId'
      path: '/integrations/$accountId'
      fullPath: '/integrations/$accountId'
      preLoaderRoute: typeof IntegrationsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/remote': {
      id: '/debug/remote'
      path: '/debug/remote'
      fullPath: '/debug/remote'
      preLoaderRoute: typeof DebugRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computers/$computerId': {
      id: '/computers/$computerId'
      path: '/computers/$computerId'
      fullPath: '/computers/$computerId'
      preLoaderRoute: typeof ComputersComputerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/oc/$accountId': {
      id: '/integrations/oc/$accountId'
      path: '/integrations/oc/$accountId'
      fullPath: '/integrations/oc/$accountId'
      preLoaderRoute: typeof IntegrationsOcAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computers/$computerId_/agents/$agentKind': {
      id: '/computers/$computerId_/agents/$agentKind'
      path: '/computers/$computerId/agents/$agentKind'
      fullPath: '/computers/$computerId/agents/$agentKind'
      preLoaderRoute: typeof ComputersComputerIdAgentsAgentKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ComputersComputerIdRoute: ComputersComputerIdRoute,
  DebugRemoteRoute: DebugRemoteRoute,
  IntegrationsAccountIdRoute: IntegrationsAccountIdRoute,
  LocalAgentsTokenIdRoute: LocalAgentsTokenIdRoute,
  LocalTokenIdRoute: LocalTokenIdRoute,
  MemoriesMemoryIdRoute: MemoriesMemoryIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BridgeIndexRoute: BridgeIndexRoute,
  ComputersIndexRoute: ComputersIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  LocalAgentsIndexRoute: LocalAgentsIndexRoute,
  LocalIndexRoute: LocalIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  IntegrationsOcAccountIdRoute: IntegrationsOcAccountIdRoute,
  ComputersComputerIdAgentsAgentKindRoute:
    ComputersComputerIdAgentsAgentKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
