/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as LocalAgentsIndexRouteImport } from './routes/local-agents.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as BridgeIndexRouteImport } from './routes/bridge.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as MemoriesMemoryIdRouteImport } from './routes/memories.$memoryId'
import { Route as LocalAgentsTokenIdRouteImport } from './routes/local-agents.$tokenId'
import { Route as IntegrationsAccountIdRouteImport } from './routes/integrations.$accountId'
import { Route as DebugRemoteRouteImport } from './routes/debug.remote'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as IntegrationsOcAccountIdRouteImport } from './routes/integrations.oc.$accountId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAgentsIndexRoute = LocalAgentsIndexRouteImport.update({
  id: '/local-agents/',
  path: '/local-agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeIndexRoute = BridgeIndexRouteImport.update({
  id: '/bridge/',
  path: '/bridge/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesMemoryIdRoute = MemoriesMemoryIdRouteImport.update({
  id: '/memories/$memoryId',
  path: '/memories/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAgentsTokenIdRoute = LocalAgentsTokenIdRouteImport.update({
  id: '/local-agents/$tokenId',
  path: '/local-agents/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAccountIdRoute = IntegrationsAccountIdRouteImport.update({
  id: '/integrations/$accountId',
  path: '/integrations/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRemoteRoute = DebugRemoteRouteImport.update({
  id: '/debug/remote',
  path: '/debug/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsOcAccountIdRoute = IntegrationsOcAccountIdRouteImport.update({
  id: '/integrations/oc/$accountId',
  path: '/integrations/oc/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/debug/remote': typeof DebugRemoteRoute
  '/integrations/$accountId': typeof IntegrationsAccountIdRoute
  '/local-agents/$tokenId': typeof LocalAgentsTokenIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/bridge/': typeof BridgeIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/local-agents/': typeof LocalAgentsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/oc/$accountId': typeof IntegrationsOcAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/debug/remote': typeof DebugRemoteRoute
  '/integrations/$accountId': typeof IntegrationsAccountIdRoute
  '/local-agents/$tokenId': typeof LocalAgentsTokenIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/agents': typeof AgentsIndexRoute
  '/bridge': typeof BridgeIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/local-agents': typeof LocalAgentsIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/oc/$accountId': typeof IntegrationsOcAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/debug/remote': typeof DebugRemoteRoute
  '/integrations/$accountId': typeof IntegrationsAccountIdRoute
  '/local-agents/$tokenId': typeof LocalAgentsTokenIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/bridge/': typeof BridgeIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/local-agents/': typeof LocalAgentsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/oc/$accountId': typeof IntegrationsOcAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/auth/verify'
    | '/debug/remote'
    | '/integrations/$accountId'
    | '/local-agents/$tokenId'
    | '/memories/$memoryId'
    | '/agents/'
    | '/bridge/'
    | '/integrations/'
    | '/local-agents/'
    | '/memories/'
    | '/skills/'
    | '/auth/google/callback'
    | '/integrations/oc/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/auth/verify'
    | '/debug/remote'
    | '/integrations/$accountId'
    | '/local-agents/$tokenId'
    | '/memories/$memoryId'
    | '/agents'
    | '/bridge'
    | '/integrations'
    | '/local-agents'
    | '/memories'
    | '/skills'
    | '/auth/google/callback'
    | '/integrations/oc/$accountId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/auth/verify'
    | '/debug/remote'
    | '/integrations/$accountId'
    | '/local-agents/$tokenId'
    | '/memories/$memoryId'
    | '/agents/'
    | '/bridge/'
    | '/integrations/'
    | '/local-agents/'
    | '/memories/'
    | '/skills/'
    | '/auth/google/callback'
    | '/integrations/oc/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  DebugRemoteRoute: typeof DebugRemoteRoute
  IntegrationsAccountIdRoute: typeof IntegrationsAccountIdRoute
  LocalAgentsTokenIdRoute: typeof LocalAgentsTokenIdRoute
  MemoriesMemoryIdRoute: typeof MemoriesMemoryIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BridgeIndexRoute: typeof BridgeIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  LocalAgentsIndexRoute: typeof LocalAgentsIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  IntegrationsOcAccountIdRoute: typeof IntegrationsOcAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-agents/': {
      id: '/local-agents/'
      path: '/local-agents'
      fullPath: '/local-agents/'
      preLoaderRoute: typeof LocalAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge/': {
      id: '/bridge/'
      path: '/bridge'
      fullPath: '/bridge/'
      preLoaderRoute: typeof BridgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$memoryId': {
      id: '/memories/$memoryId'
      path: '/memories/$memoryId'
      fullPath: '/memories/$memoryId'
      preLoaderRoute: typeof MemoriesMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-agents/$tokenId': {
      id: '/local-agents/$tokenId'
      path: '/local-agents/$tokenId'
      fullPath: '/local-agents/$tokenId'
      preLoaderRoute: typeof LocalAgentsTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$accountId': {
      id: '/integrations/$accountId'
      path: '/integrations/$accountId'
      fullPath: '/integrations/$accountId'
      preLoaderRoute: typeof IntegrationsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/remote': {
      id: '/debug/remote'
      path: '/debug/remote'
      fullPath: '/debug/remote'
      preLoaderRoute: typeof DebugRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/oc/$accountId': {
      id: '/integrations/oc/$accountId'
      path: '/integrations/oc/$accountId'
      fullPath: '/integrations/oc/$accountId'
      preLoaderRoute: typeof IntegrationsOcAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  DebugRemoteRoute: DebugRemoteRoute,
  IntegrationsAccountIdRoute: IntegrationsAccountIdRoute,
  LocalAgentsTokenIdRoute: LocalAgentsTokenIdRoute,
  MemoriesMemoryIdRoute: MemoriesMemoryIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BridgeIndexRoute: BridgeIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  LocalAgentsIndexRoute: LocalAgentsIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  IntegrationsOcAccountIdRoute: IntegrationsOcAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
