// Extension → shiki language, with a statically-analyzable lazy loader per
// language so Vite splits each grammar into its own chunk. Curated to common
// languages; anything else falls back to plain text (which is still a valid
// preview, never an error).

type LangLoader = () => Promise<unknown>;

export const LANG_BY_EXT: Record<string, string> = {
	ts: "typescript",
	tsx: "tsx",
	js: "javascript",
	jsx: "jsx",
	mjs: "javascript",
	cjs: "javascript",
	json: "json",
	jsonc: "jsonc",
	py: "python",
	rb: "ruby",
	go: "go",
	rs: "rust",
	java: "java",
	kt: "kotlin",
	c: "c",
	h: "c",
	cpp: "cpp",
	cc: "cpp",
	hpp: "cpp",
	cs: "csharp",
	php: "php",
	sh: "shellscript",
	bash: "shellscript",
	zsh: "shellscript",
	sql: "sql",
	yaml: "yaml",
	yml: "yaml",
	toml: "toml",
	xml: "xml",
	html: "html",
	css: "css",
	scss: "scss",
	md: "markdown",
	markdown: "markdown",
	swift: "swift",
	dockerfile: "docker",
	vue: "vue",
	svelte: "svelte",
};

export const LANG_LOADERS: Record<string, LangLoader> = {
	typescript: () => import("shiki/langs/typescript.mjs"),
	tsx: () => import("shiki/langs/tsx.mjs"),
	javascript: () => import("shiki/langs/javascript.mjs"),
	jsx: () => import("shiki/langs/jsx.mjs"),
	json: () => import("shiki/langs/json.mjs"),
	jsonc: () => import("shiki/langs/jsonc.mjs"),
	python: () => import("shiki/langs/python.mjs"),
	ruby: () => import("shiki/langs/ruby.mjs"),
	go: () => import("shiki/langs/go.mjs"),
	rust: () => import("shiki/langs/rust.mjs"),
	java: () => import("shiki/langs/java.mjs"),
	kotlin: () => import("shiki/langs/kotlin.mjs"),
	c: () => import("shiki/langs/c.mjs"),
	cpp: () => import("shiki/langs/cpp.mjs"),
	csharp: () => import("shiki/langs/csharp.mjs"),
	php: () => import("shiki/langs/php.mjs"),
	shellscript: () => import("shiki/langs/shellscript.mjs"),
	sql: () => import("shiki/langs/sql.mjs"),
	yaml: () => import("shiki/langs/yaml.mjs"),
	toml: () => import("shiki/langs/toml.mjs"),
	xml: () => import("shiki/langs/xml.mjs"),
	html: () => import("shiki/langs/html.mjs"),
	css: () => import("shiki/langs/css.mjs"),
	scss: () => import("shiki/langs/scss.mjs"),
	markdown: () => import("shiki/langs/markdown.mjs"),
	swift: () => import("shiki/langs/swift.mjs"),
	docker: () => import("shiki/langs/docker.mjs"),
	vue: () => import("shiki/langs/vue.mjs"),
	svelte: () => import("shiki/langs/svelte.mjs"),
};

/** Extensions the code viewer claims (beyond text/* mime). */
export const CODE_EXTENSIONS = new Set([
	...Object.keys(LANG_BY_EXT),
	"txt",
	"log",
	"csv",
	"env",
	"ini",
	"conf",
	"gitignore",
]);
